# Generated by Django 3.2.7 on 2021-11-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bike',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='card',
            field=models.IntegerField(),
        ),
    ]
